export interface Review {
  id: string;
  author: string;
  rating: number;
  text: string;
  date: string;
}

export interface Product {
  id: number;
  name: string;
  category: "Laptops" | "Phones" | "Audio" | "Gaming";
  price: number;
  description: string;
  tags: string[];
  imageUrl: string;
  rating: number;
  reviews: Review[];
}

export const products: Product[] = [
  // --- LAPTOPS ---
  {
    id: 1,
    name: "SwiftBook Air 14",
    category: "Laptops",
    price: 549,
    description: "A feather-light budget laptop with an AMD Ryzen 5 processor, 8GB RAM, and 256GB SSD. Ideal for students and remote workers who need all-day battery life and portability.",
    tags: ["budget", "lightweight", "AMD"],
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=2626&auto=format&fit=crop",
    rating: 4.2,
    reviews: [
      { id: "r1", author: "Alex J.", rating: 5, text: "Unbelievable value for the price. The battery really does last all day.", date: "2024-01-15" },
      { id: "r2", author: "Sarah M.", rating: 4, text: "Great for school, a bit slow for heavy gaming but that's expected.", date: "2024-02-01" }
    ],
  },
  {
    id: 2,
    name: "ProBeast Gaming Laptop G7",
    category: "Laptops",
    price: 1499,
    description: "Dominate every game with an Intel Core i7-13700H, RTX 4060 GPU, 32GB RAM, and a stunning 165Hz QHD display.",
    tags: ["gaming", "RTX", "high-performance"],
    imageUrl: "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?q=80&w=2642&auto=format&fit=crop",
    rating: 4.8,
    reviews: [
      { id: "r3", author: "Gamer99", rating: 5, text: "The RTX 4060 is a beast. 1440p gaming is smooth as butter.", date: "2024-02-10" }
    ],
  },
  {
    id: 3,
    name: "ThinEdge Ultra Slim",
    category: "Laptops",
    price: 899,
    description: "An ultra-slim productivity laptop with an edge-to-edge OLED display, Intel Core i5, 16GB RAM, and dual Thunderbolt 4 ports.",
    tags: ["ultrabook", "OLED", "productivity"],
    imageUrl: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=2671&auto=format&fit=crop",
    rating: 4.5,
    reviews: [
      { id: "r4", author: "DesignGuy", rating: 5, text: "That OLED screen is gorgeous. Best laptop I've owned.", date: "2024-01-20" }
    ],
  },
  {
    id: 4,
    name: "DevStation Pro 16",
    category: "Laptops",
    price: 1899,
    description: "Built for engineers. Features a 16-inch Mini-LED display, 64GB RAM, and a massive 2TB SSD for handling massive codebases and docker containers.",
    tags: ["developer", "powerhouse", "mac-alternative"],
    imageUrl: "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?q=80&w=2670&auto=format&fit=crop",
    rating: 4.9,
    reviews: [
      { id: "r5", author: "LeadDev", rating: 5, text: "Finally enough RAM for all my Docker containers!", date: "2024-02-15" }
    ],
  },
  {
    id: 5,
    name: "FlexiBook 360",
    category: "Laptops",
    price: 749,
    description: "A versatile 2-in-1 convertible laptop. Flip it into tent mode for movies, tablet mode for drawing, or standard laptop mode for typing. Features a touch screen and included stylus.",
    tags: ["2-in-1", "touchscreen", "versatile"],
    imageUrl: "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?q=80&w=2664&auto=format&fit=crop",
    rating: 4.3,
    reviews: [
      { id: "r6", author: "Artie", rating: 4, text: "The stylus is very responsive. Great for sketching on the go.", date: "2024-01-05" }
    ],
  },
  {
    id: 6,
    name: "CloudBook Basic",
    category: "Laptops",
    price: 299,
    description: "A simple, secure, and blazing fast machine designed purely for web browsing and cloud applications. Perfect for schools and basic home usage.",
    tags: ["budget", "chromeos", "student"],
    imageUrl: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?q=80&w=2670&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 7,
    name: "Studio Creator Z",
    category: "Laptops",
    price: 2299,
    description: "A visual masterpiece for video editors and 3D artists. Factory color-calibrated 4K display, dialed-in precision trackpad, and an RTX 4080.",
    tags: ["creator", "4K", "video-editing"],
    imageUrl: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?q=80&w=2670&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },

  // --- PHONES ---
  {
    id: 8,
    name: "ZenX Budget Phone",
    category: "Phones",
    price: 199,
    description: "A reliable budget smartphone with a 6.5-inch LCD, quad-core processor, 64GB storage, and an massive two-day 5000mAh battery.",
    tags: ["budget", "battery", "Android"],
    imageUrl: "https://images.unsplash.com/photo-1598327105666-5b89351cb31b?q=80&w=2600&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 9,
    name: "Alpha Phone 12 Pro",
    category: "Phones",
    price: 1099,
    description: "The flagship experience. Features a titanium frame, triple-camera system with 100x zoom, and an ultra-bright 120Hz LTPO OLED display.",
    tags: ["flagship", "camera", "titanium"],
    imageUrl: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=2670&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 10,
    name: "FoldMaster Z3",
    category: "Phones",
    price: 1599,
    description: "The future is foldable. Opens up into a massive 7.6-inch tablet display for intense multitasking, while folding down into a pocketable narrow block.",
    tags: ["foldable", "innovation", "multitasking"],
    imageUrl: "https://images.unsplash.com/photo-1662485642442-7a2e79603099?q=80&w=2670&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 11,
    name: "GamerPhone Red",
    category: "Phones",
    price: 799,
    description: "Built strictly for mobile gaming. Includes physical shoulder triggers, an active cooling fan attachment, and a blazingly fast 165Hz screen.",
    tags: ["gaming", "triggers", "cooling"],
    imageUrl: "https://images.unsplash.com/photo-1601784551446-20c9e07cd8d3?q=80&w=2526&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 12,
    name: "EcoPhone Recycled",
    category: "Phones",
    price: 499,
    description: "A sustainable smartphone made from 90% recycled plastics. Features modular components that you can easily swap yourself to reduce electronic waste.",
    tags: ["sustainable", "modular", "eco-friendly"],
    imageUrl: "https://images.unsplash.com/photo-1549439602-43ebca2327af?q=80&w=2670&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 13,
    name: "Nova Lite 5G",
    category: "Phones",
    price: 349,
    description: "Bringing blazing fast 5G speeds to the masses. A gorgeous mid-range device with an edge-to-edge screen, punch-hole camera, and sleek glass back.",
    tags: ["5G", "mid-range", "sleek"],
    imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=2600&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 14,
    name: "PixelPerfect CameraEdition",
    category: "Phones",
    price: 899,
    description: "Pure Android software with the best computational photography system in the world. Unmatched low-light performance and skin tone accuracy.",
    tags: ["photography", "pure-android", "AI-camera"],
    imageUrl: "https://images.unsplash.com/photo-1598327105854-3c66f2b740e7?q=80&w=2600&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },

  // --- AUDIO ---
  {
    id: 15,
    name: "EchoBass Over-Ear",
    category: "Audio",
    price: 129,
    description: "Affordable over-ear headphones featuring thumping bass, 30-hour battery life, and comfortable memory foam earcups.",
    tags: ["budget", "bass", "wireless"],
    imageUrl: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?q=80&w=2664&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 16,
    name: "SilencePro ANC Earbuds",
    category: "Audio",
    price: 249,
    description: "Premium true wireless earbuds with industry-leading Active Noise Cancellation. Block out airplane engines or loud offices instantly.",
    tags: ["ANC", "earbuds", "premium"],
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=2670&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 17,
    name: "StudioMonitor 50X",
    category: "Audio",
    price: 179,
    description: "A flat-response wired headphone beloved by music producers and audiophiles for its surgically accurate sound recreation.",
    tags: ["wired", "audiophile", "flat-response"],
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=2670&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 18,
    name: "SportBuds WaterResist",
    category: "Audio",
    price: 89,
    description: "Rugged and fully waterproof wireless earbuds featuring over-ear hooks so they never fall out during intense workouts or rain runs.",
    tags: ["sports", "waterproof", "secure-fit"],
    imageUrl: "https://images.unsplash.com/photo-1583394838336-acd977736f90?q=80&w=2584&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 19,
    name: "Retro Vinyl Player",
    category: "Audio",
    price: 299,
    description: "A gorgeous walnut wood-finish record player that combines classic analog warmth with built-in modern Bluetooth streaming capabilities.",
    tags: ["vinyl", "retro", "bluetooth"],
    imageUrl: "https://images.unsplash.com/photo-1603539947678-ebda01c3cbf9?q=80&w=2670&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 20,
    name: "Desktop Soundbar Mini",
    category: "Audio",
    price: 119,
    description: "A sleek, low-profile soundbar that slides perfectly under your monitor, filling your room with rich, 3D spatial audio.",
    tags: ["speakers", "desktop", "compact"],
    imageUrl: "https://images.unsplash.com/photo-1545454675-3531b543be5d?q=80&w=2670&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 21,
    name: "Podcaster Pro Mic",
    category: "Audio",
    price: 159,
    description: "A professional USB condenser microphone built for streamers and podcasters. Features a built-in pop filter and zero-latency monitoring.",
    tags: ["microphone", "streaming", "USB"],
    imageUrl: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?q=80&w=2574&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },

  // --- GAMING ---
  {
    id: 22,
    name: "Vortex Pro Gaming Mouse",
    category: "Gaming",
    price: 79,
    description: "A precision gaming mouse with a 25K DPI optical sensor, 7 programmable buttons, RGB lighting, and an ultra-light honeycomb design at just 68g.",
    tags: ["mouse", "RGB", "lightweight", "precision"],
    imageUrl: "https://images.unsplash.com/photo-1527814050087-379381547969?q=80&w=2670&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 23,
    name: "MechKey 104 Mechanical Keyboard",
    category: "Gaming",
    price: 129,
    description: "A full-sized mechanical keyboard with tactile Cherry MX Brown switches, aircraft-grade aluminum frame, and per-key customizable RGB.",
    tags: ["keyboard", "mechanical", "tactile"],
    imageUrl: "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=2671&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 24,
    name: "Ergo Throne Gaming Chair",
    category: "Gaming",
    price: 349,
    description: "Say goodbye to back pain. This high-density memory foam chair includes lumbar support cushions, 4D armrests, and a 165-degree recline.",
    tags: ["chair", "ergonomic", "comfort"],
    imageUrl: "https://images.unsplash.com/photo-1598550476439-6847785fcea6?q=80&w=2574&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 25,
    name: "UltraWide Curved Monitor 34\"",
    category: "Gaming",
    price: 499,
    description: "Immerse yourself completely. A 34-inch ultrawide 1440p monitor with a deep 1000R curve, 144Hz refresh rate, and 1ms response time.",
    tags: ["monitor", "ultrawide", "144Hz"],
    imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=2670&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 26,
    name: "ConsoleNext Gen X",
    category: "Gaming",
    price: 499,
    description: "Experience true 4K resolution gaming at 60 FPS. Features blazing fast NVMe storage that eliminates loading screens.",
    tags: ["console", "4K", "next-gen"],
    imageUrl: "https://images.unsplash.com/photo-1605901309584-818e25960b8f?q=80&w=2638&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 27,
    name: "VR Headset Max",
    category: "Gaming",
    price: 399,
    description: "A standalone virtual reality headset requiring no PC. Step into entirely new worlds with 4K per-eye resolution and precision hand tracking.",
    tags: ["VR", "immersion", "standalone"],
    imageUrl: "https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?q=80&w=2670&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
  {
    id: 28,
    name: "Arcade Fight Stick Pro",
    category: "Gaming",
    price: 189,
    description: "Built for fighting game enthusiasts. Features genuine Sanwa Denshi joystick and buttons mounted on a solid steel base.",
    tags: ["controller", "arcade", "fighting-games"],
    imageUrl: "https://images.unsplash.com/photo-1593305841991-05c297ba4575?q=80&w=2557&auto=format&fit=crop",
    rating: 4.5,
    reviews: [],
  },
];
